# Setup
title:              Symmetric Models for Visual-Force Learning 
tagline:             ''
description:         ''
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Colin Kohler
  url:               colinkohler.github.io 
  email:             kohler.c@northeastern.edu 

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
