import torch
import numpy as np
import numpy.random as npr

from midichlorians.models.sac import Critic, GaussianPolicy

class SACAgent(object):
  '''
  Soft Actor-Critic Agent.

  Args:
    config (dict): Task config.
    device (torch.Device): Device to use for inference (cpu or gpu)
    training (bool): Flag indicating if the agent is being trained or not. Defaults to False.
  '''
  def __init__(self, config, device):
    self.config = config
    self.device = device

    self.actor = GaussianPolicy(self.config.obs_channels, self.config.action_dim)
    self.actor.to(self.device)
    self.actor.eval()

    self.critic = Critic(self.config.obs_channels, self.config.action_dim)
    self.critic.to(self.device)
    self.critic.eval()

  def selectAction(self, obs, evaluate=False):
    '''
    Get the action from the policy.

    Args:
      obs (numpy.array): The current observation

    Returns:
      numpy.array : The action generated by the policy
    '''
    obs = torch.Tensor(obs.astype(np.float32)).view(1, 1, 128, 128).to(self.device)

    with torch.no_grad():
      if evaluate:
        _, _, action = self.actor.sample(obs)
      else:
        action, _, _ = self.actor.sample(obs)

    value = self.critic(obs, action)

    return action, value

  def setWeights(self, weights):
    '''
    Load given weights into the actor and critic

    Args:
      weights (dict, dict): Model weights to load
    '''
    self.actor.load_state_dict(weights[0])
    self.critic.load_state_dict(weights[1])
